# This defines the script engine
# Lines starting with "#" are comments
# Parameter format: PARAM_NAM="value"; this format must be followed!
# Do not delete parameters not marked as optional, to avoid unnecessary errors
#
# The parser for this config file is simplistic; never append comments after parameter lines
# Incorrect example
#           param_name="value" # Parameter description
# Correct example
#           # Parameter description
#           param_name="value"


# Core executor core_executor
# This is the entry point for kr-script execution
executor_core="file:///android_asset/kr-script/executor.sh"

# Page list config file (can be empty)
page_list_config="file:///android_asset/kr-script/more.xml"

# Toolkit directory (for busybox and other tools)
toolkit_dir="file:///android_asset/toolkit"
