#!/usr/bin/env python3
"""Build docs/UI-MAP.md from docs/ui/*.json (run after tools/ui-map.sh)."""
import glob, json, os

out = ["# UI-MAP — screens, tap targets and coordinates (1080x2400)", ""]
out.append("Generated by `bash tools/ui-map.sh`; tap with `bash tools/agent-tap.sh <screen> <text|id:part>`.")
out.append("")
for path in sorted(glob.glob("docs/ui/*.json")):
    name = os.path.basename(path)[:-5]
    nodes = json.load(open(path))
    out.append(f"## {name}")
    out.append("")
    out.append(f"![{name}](ui/{name}.png)")
    out.append("")
    out.append("| element | id | tap (x,y) |")
    out.append("|---|---|---|")
    count = 0
    for n in nodes:
        if not n.get("clickable"):
            continue
        label = (n.get("text") or n.get("desc") or "").replace("|", "/").strip()
        if not label and not n.get("id"):
            continue
        count += 1
        if count > 40:
            break
        out.append(f"| {label[:48]} | {n.get('id','')} | {n['bounds']['cx']},{n['bounds']['cy']} |")
    out.append("")
open("docs/UI-MAP.md", "w").write("\n".join(out))
print("docs/UI-MAP.md written")
