[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet-therm-adc	xo-therm-adc	conn-therm-adc
weight		4		2		1
polling		1000

[PHONE-SS-CPU6-0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		33000
clr		32000
target		1324800

[PHONE-SS-CPU6-1]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		54000
clr		52000
target		979200

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		25000	60000
clr		24000	48000
target		1414	1515

[PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		58000
clr		50000
target		5

[PHONE-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		43000	45000	48000
clr		41000	43000	45000
target		0	1	2

[PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		25000
clr		24000
target		1

[PHONE-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[PHONE-MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7+backlight
polling		1000
trig		55000
clr		53000
target		1+1+1536
