[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet-therm-adc	xo-therm-adc	conn-therm-adc
weight		4		2		1
polling		1000

[NL-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		500
trig		51000
clr		50000
target		1094400

[NL-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		35000	39000	42000	60000
clr		34000	38000	41000	48000
target          900     1002    1408    1515

[NL-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		60000
clr		50000
target		5

[NL-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		51000
clr		48000
target		1

[NL-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[NL-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		51000
clr		48000
target		2
