[VIRTUAL-SENSOR]
algo_type	virtual
sensors		nvm-therm-adc
weight		1
polling		1000

[SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		500
trig		52000
clr			50000
target		1209600

[SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		50000
clr			48000
target		979200

[MONITOR-hotplug]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		52000
clr			50000
target		1+1

[MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		50000
clr			48000
target		2

[MONITOR-BAT]
algo_type	monitor
sensor		quiet-therm-adc
device		battery
polling		1000
trig		38000	39000	40000	41000	42000	43000	44000	45000
clr		    37000	38000	39000	40000	41000	42000	43000	44000
target      201		602		907		1312	1312	1313	1414	1515

[MONITOR-LCD]
algo_type	monitor
sensor		backlight_therm
device		backlight
polling		1000
trig		40000	44000	47000
clr			38000	42000	45000
target		410		819		1230

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		quiet-therm-adc
device		temp_state
polling		1000
trig		60000
clr			58000
target		4

[MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu0+hotplug_cpu1
polling		1000
trig		5
clr			6
target		1+1
reverse		1

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		quiet-therm-adc
device		hotplug_cpu6+hotplug_cpu7+backlight
polling		1000
trig		61000
clr			58000
target		1+1+2048
