[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet-therm-adc	xo-therm-adc	conn-therm-adc
weight		4		2		1
polling		1000

[4K-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		38000		44000		51000
clr		37000		43000		50000
target		1843200		1555200		1094400

[4K-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		55000
clr		53000
target		5

[4K-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		53000
clr		48000
target		1

[4K-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[4K-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		53000
clr		48000
target		2

[4K-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		35000	39000	42000	60000
clr		34000	38000	41000	48000
target          900     1002    1408    1515

[4K-MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu5+hotplug_cpu6+hotplug_cpu7+backlight
polling		1000
trig		55000
clr		53000
target		1+1+1+1024
